### PR TITLE
Replace bitwise operands with Structs for performance

### LINKED ISSUE #24: Virtual Jaguar has slowdown on low end hardware from 2.1.1 to 2.1.2
Virtual Jaguar has slowdown on low end hardware (Intel Atom) from 2.1.1 to 2.1.2. This slowdown is present in the SDL Port as well. Can this be bisected to find out what cause this slowdown?

### LINKED ISSUE #38: [spike] Emulator needs massive improvements
Ok, so I tested out a bunch of Jaguar games and noticed a lot of them are broken or have issues. And decided to make a list of which ones have issues. This emulator seems to need a lot of work.

Air Cars
Half the title screen is cut off
Air Cars

Atari Karts
Weird bar down the side of the screen during the game
Atari Karts

Battlesphere Gold
Only loads if Bios is enabled. But menus are glitched - black screen after menu, game doesn't work at all
Battlesphere

Club Drive
Half the title screen is cut off and textures are missing.
Club Drive
Club Drive 2

Cybermorph
Missing/glitched textures
Cybermorph

Doom
Weird bar down half of the screen during the game
Doom

Fight for Life
Flickering graphics, mainly in the menu
Fight for Life

Flashback - Quest for Identity
Game displays on the left side of the screen
Flashback - Quest for Identity
Flashback Quest for Identity 2

Hover Strike
Glitched and flickering graphics
Hover Strike
Hover Strike 2

Hyper Force
Black screen after title, doesn't work at all

I-War
Half the title screen is cut off, glitched and flickering graphics
I-War
I-War 2

Iron Soldier
Black screen after character selection, doesn't work at all

Iron Soldier 2
Title displays on the left side of the screen, black screen after title but music still plays, doesn't work at all
Iron Soldier 2

Kasumi Ninja
Severe Graphics issues, flickering at the title screen, missing textures, black screen freezes
Kasumi Ninja
Kasumi Ninja2

Missile Command 3D
Some minor graphics glitches/flickering. Nothing too serious.
Missile Command 3D

NBA Jam - Tournament Edition
Some minor occasional screen jumping, nothing too serious.

Pinball Fantasies
Some of the introduction screens are cut off
Pinball Fantasies

Powerdrive Rally
Some of the introduction screens are cut off, game crashes upon starting a new game
Powerdrive Rally

Raiden
Only works if the BIOS is enabled, otherwise black screen freezes

Ruiner Pinball
Black screen, doesn't work at all

Skyhammer
Works but freezes during game

Super Burnout
Some of the letters are cut off, black screen doesnt work at all when starting a new game
Super Burnout

Supercross 3D
Displays on the left side of the screen, blurry textures
Supercross 3D

Syndicate
Works good, but there are pink patches in the writing
Syndicate

Tempest 2000
Works good, but there's some minor flickering occasionally

Towers II
Unplayable due to flickering/flashing

Trevor McFur in the Crescent Galaxy
Half the screen is cut off during the loading screen
Trevor McFur in the Crescent Galaxy

Val D'isere Skiing and Snowboarding
Game displays on the left side of the screen
Val D'isere Skiing and Snowboarding

White Men Can't Jump
Black screen, doesn't work at all

Wolfenstein 3D
Black screen, doesn't work at all

Zero 5
Game works good, but some mild flickering

Zoop
Game crashes and doesn't work

### LINKED ISSUE #51: [game] DOOM runs too slow
Even when the emulation speed is 100%, DOOM's frame rate is way worse than the real console. Normally the game should run much faster/smoother.

### PR DESCRIPTION
**Pull request by JoeMatt**

### CODE REVIEW

**Comment by JoeMatt** [comment]
Ready for review
Tested Doom, NBA Jam and Tempest 2000

**Comment by twinaphex** [comment]
I'm testing it on Windows 10/11, on an intel x64 CPU.

**Comment by twinaphex** [comment]
This is simply a no-go in its current state. Too many things are changed, not enough testing has been done outside of Mac/iOS, the regressions that already exist with this are already way too high and the chance for future regressions even higher still.

This entire PR needs to be entirely redone from the ground up and split up into bite-sized chunks that each get tested on at least Windows, Linux, and Mac. Just testing it on Mac alone and then only on ARM is simply not going to lead to results that can eventually be merged, libretro targets way more systems than just that.

**Comment by JoeMatt** [comment]
I'm well aware of that. This PR is the last part of the already split up larger PR. I have testing environments for other arches. I've just been busy with holidays and job interviews. 

There's a reason this is still marked draft.

**Comment by twinaphex** [comment]
OK, it being split up in 3 parts like that would be better, and would allow us to test easier for regressions across platforms.

**Pull request closed without merging**
